[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0xec7f5bab92a8fc441ec84777de2402688f7589ef0de417941f89e665f8729aad'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]